apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-hw03.fullname" . }}-deployment
  labels:
  {{- include "otus-hw03.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-hw03.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "otus-hw03.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.application.deployment.pod.repository}}:{{ .Values.application.deployment.pod.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.application.deployment.pod.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: {{ .Chart.Name }}-secret
          livenessProbe:
            httpGet:
              port: {{ .Values.application.deployment.pod.port }}
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: {{ .Values.application.deployment.pod.port }}
              path: /health
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-hw03.fullname" . }}-service
  labels:
  {{- include "otus-hw03.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "otus-hw03.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.service.port }}
      targetPort: http
      name: web
  type: {{ .Values.application.service.type }}
