apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s:%s/%s"
    .Values.postgresql.postgresqlUsername
    .Values.postgresql.postgresqlPassword
    (include "postgresql.fullname" .)
    .Values.postgresql.service.port
    .Values.postgresql.postgresqlDatabase
    | b64enc | quote }}

  AUTH_SECRET: bXktc3RyaW5n