apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}-consumer
spec:
  replicas: {{ .Values.consumer.deployment.replicaCount }}
  selector:
    matchLabels:
  {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: check-db-readiness
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port | quote }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: {{ .Chart.Name }}-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: {{ .Chart.Name }}-secret
            - name: KAFKA_HOST
              value: {{ .Values.kafka.dns }}