global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hw02'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'localhost:8080'