auth:
  username: postgres
  postgresPassword: postgres
  database: order
primary:
  service:
    type: LoadBalancer
    ports:
      postgresql: "5432"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true