application:
  deployment:
    pod:
      repository: khaydarov95/otus-hw06-user-app
      pullPolicy: Never
      tag: v1
      port: 80
      replicaCount: 1
  service:
    type: LoadBalancer
    port: 8080