{
 "title": "Application dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint, method) (rate(hw03_app_request_count{exported_endpoint=~\"/user(/.*)?\"}[1m]))",
     "legendFormat": "{{ method }} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency by endpoints (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint, method) \n         (rate(hw03_app_request_latency_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ method }} {{ exported_endpoint }} "
    }
   ]
  },
  {
   "title": "Responses by http_status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_status, method) (rate(hw03_app_request_count[1m]))",
     "legendFormat": "{{ method }} {{ http_status }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(hw03_app_request_count{http_status=\"500\"}[1m]) / rate(hw03_app_request_count[1m])",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}