{
 "title": "Ingress Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingress RPS by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status, path, method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{ method }} {{ status }}"
    }
   ]
  },
  {
   "title": "Ingress latency by path (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, path, method, status) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{ method }} {{ path }} {{ status }} "
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (controller_class) (rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))) / (sum by (controller_class) (rate(nginx_ingress_controller_request_duration_seconds_count[1m])))"
    }
   ]
  }
 ]
}