apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migration
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-migration
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-readiness
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port | quote }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ .Chart.Name }}-post-install-migration-job
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: {{ .Chart.Name }}-secret
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - ./migration