apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
{{- if .Values.metrics.serviceMonitor.enabled }}
    servicemonitor: enabled
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.pod.port }}
      protocol: TCP
      name: http
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
