apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Chart.Type }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Chart.Type }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.application.deployment.pod.repository}}:{{ .Values.application.deployment.pod.tag }}
          ports:
            - name: web
              containerPort: {{ .Values.application.deployment.pod.port }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: {{ .Chart.Name }}-secret
          livenessProbe:
            httpGet:
              port: {{ .Values.application.deployment.pod.port }}
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: {{ .Values.application.deployment.pod.port }}
              path: /health
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Chart.Type }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.service.port }}
      targetPort: {{ .Values.application.deployment.pod.port }}
  type: {{ .Values.application.service.type }}